name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Windows binary
      run: GOOS=windows GOARCH=amd64 go build -o win-amd64-IC2cropbruteforcer
    - name: Build Linux binary
      run: go build -o lin-amd64-IC2cropbruteforcer
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows binary
        path: win-amd64-IC2cropbruteforcer
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux binary
        path: lin-amd64-IC2cropbruteforcer
